name: Terraform Lint
on:
  pull_request:
    paths:
      - "infra/terraform/**"
  push:
    branches:
      - "main"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  terraform-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Cache plugin dir
        id: cache-tflint-plugin
        uses: actions/cache@v5
        with:
          path: ~/.tflint.d/plugins
          key: tflint-${{ hashFiles('infra/terraform/.tflint.hcl') }}
      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v6
        with:
          tflint_version: v0.61.0
      - name: Init TFLint
        if: steps.cache-tflint-plugin.outputs.cache-hit != 'true'
        working-directory: infra/terraform
        run: tflint --init
        env:
          # https://github.com/terraform-linters/tflint/blob/master/docs/user-guide/plugins.md#avoiding-rate-limiting
          GITHUB_TOKEN: ${{ github.token }}
      - name: Lint with tflint
        working-directory: infra/terraform
        run: tflint --recursive
      - name: Scan Terraform with Trivy
        uses: aquasecurity/trivy-action@v0.30.0
        with:
          scan-type: config
          scan-ref: infra/terraform
          exit-code: 1
          severity: HIGH,CRITICAL
          format: table
